{
 "title": "Distributed Rate Limiter",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Allowed Requests (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rate_limit_requests_total{status=\"allowed\"}[1m])",
     "legendFormat": "Allowed - {{type}}"
    }
   ]
  },
  {
   "title": "Blocked/Invalid Requests (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(rate_limit_requests_total{status=\"blocked\"}[1m])",
     "legendFormat": "Blocked 429 - {{type}}"
    },
    {
     "expr": "rate(rate_limit_requests_total{status=\"invalid\"}[1m])",
     "legendFormat": "Invalid 401 - {{type}}"
    }
   ]
  },
  {
   "title": "Redis Lua Script Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(rate_limit_redis_latency_seconds_bucket[1m])) by (le, type))",
     "legendFormat": "p95 Redis latency - {{type}}"
    }
   ]
  }
 ]
}